### ISSUE TITLE
Not working on macOS 12.3

### ISSUE THREAD

**Issue by LampPrinter** [bskim45/alfred-coin-ticker#1]
Code 127: /bin/bash: python: command not found

https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/

**Comment by bskim45** [comment]
This workflow is based on the top of https://github.com/deanishe/alfred-workflow. Once alfred-workflow adds support for macOS 12.3, we can move forward. https://github.com/deanishe/alfred-workflow/issues/182

**Comment by bskim45** [comment]
fixed in [2.0.0](https://github.com/bskim45/alfred-coin-ticker/releases/tag/2.0.0)
